name: Docker

on:
  workflow_call:

jobs:

  docker:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Build
      uses: docker/setup-buildx-action@v3.10.0

    - name: Download a Build Artifact
      uses: actions/download-artifact@v4.3.0
      with:
        name: api em go

    - name: Docker Login
      uses: docker/login-action@v3.4.0
      with:
        username: lucapinheiro
        password: ${{ secrets.PASSWOORD_DOCKER_HUB }} 

    - name: Build and push Docker images
      uses: docker/build-push-action@v6.16.0
      with:
        context: .
        file: ./Dockerfle
        push: true
        tags: lucapinheiro/go_ci:${{ github.ref_name }}
          
                      
          
      
